/// This file is auto-generated by scripts/set_platform.dart
/// Do not modify manually.
///
/// Current Platform: Mobile (ffmpeg_kit_flutter_new)

export 'package:ffmpeg_kit_flutter_new/ffmpeg_kit.dart';
export 'package:ffmpeg_kit_flutter_new/return_code.dart';
export 'package:ffmpeg_kit_flutter_new/session.dart';
export 'package:ffmpeg_kit_flutter_new/log.dart';
export 'package:ffmpeg_kit_flutter_new/statistics.dart';
