import 'dart:io';

void main(List<String> args) {
  if (args.isEmpty) {
    print('Usage: dart scripts/set_platform.dart [mobile|desktop]');
    exit(1);
  }

  final target = args[0].toLowerCase();
  final isMobile = target == 'mobile';
  final isDesktop = target == 'desktop';

  if (!isMobile && !isDesktop) {
    print('Invalid platform. Use "mobile" or "desktop".');
    exit(1);
  }

  print('Switching implementation to: ${isMobile ? "Modern (Android/iOS/macOS)" : "Legacy (Linux/Windows)"}...');

  // 1. Update pubspec.yaml
  updatePubspec(isMobile);

  // 2. Update ffmpeg_shim.dart
  updateShim(isMobile);

  // 3. Run pub get
  print('Running flutter pub get...');
  final result = Process.runSync('flutter', ['pub', 'get'], runInShell: true);
  stdout.write(result.stdout);
  stderr.write(result.stderr);

  print('Done! Ready for ${isMobile ? "Android/iOS/macOS" : "Linux/Windows"}.');
}

void updatePubspec(bool isMobile) {
  final file = File('pubspec.yaml');
  final lines = file.readAsLinesSync();
  final newLines = <String>[];
  bool inDependencies = false;
  bool isDevDependencies = false;

  for (final line in lines) {
    if (line.trim() == 'dependencies:') {
      inDependencies = true;
    } else if (line.trim() == 'dev_dependencies:') {
      isDevDependencies = true;
      inDependencies = false;
    }

    // Filter out both versions to re-add the correct one
    if (inDependencies && !isDevDependencies) {
      if (line.trim().startsWith('ffmpeg_kit_flutter_new:') ||
          line.trim().startsWith('ffmpeg_kit_flutter_full_gpl:')) {
        continue;
      }
    }
    
    newLines.add(line);
  }

  // Find where to insert the dependency (e.g., after 'dependencies:')
  final depIndex = newLines.indexWhere((l) => l.trim() == 'dependencies:');
  if (depIndex != -1) {
    final dependency = isMobile
        ? '  ffmpeg_kit_flutter_new: ^4.1.0'
        : '  ffmpeg_kit_flutter_full_gpl: ^6.0.3';
    newLines.insert(depIndex + 1, dependency);
  }

  file.writeAsStringSync(newLines.join('\n') + '\n');
  print('Updated pubspec.yaml');
}

void updateShim(bool isMobile) {
  final file = File('lib/core/utils/ffmpeg_shim.dart');
  final package = isMobile ? 'ffmpeg_kit_flutter_new' : 'ffmpeg_kit_flutter_full_gpl';
  
  final content = '''
/// This file is auto-generated by scripts/set_platform.dart
/// Do not modify manually.
///
/// Current Platform: ${isMobile ? "Mobile (ffmpeg_kit_flutter_new)" : "Desktop (ffmpeg_kit_flutter_full_gpl)"}

export 'package:$package/ffmpeg_kit.dart';
export 'package:$package/return_code.dart';
export 'package:$package/session.dart';
export 'package:$package/log.dart';
export 'package:$package/statistics.dart';
''';

  file.writeAsStringSync(content);
  print('Updated lib/core/utils/ffmpeg_shim.dart');
}
