#!/bin/bash
set -e

# Configuration
APP_NAME="tvmax"
BUILD_DIR="../build/linux/x64/release/bundle"
APP_DIR="AppDir"
ICON_PATH="../assets/icon/icon_master.png"

echo "Starting AppImage creation for $APP_NAME..."
...
echo "Copying build files..."
...
echo "Copying metadata..."
...
echo "Icon not found. Creating placeholder."
...
echo "Downloading appimagetool..."
...
echo "Downloading AppImage runtime..."
...
echo "Generating AppImages..."
...
echo "Creating $VARIANT version..."
...
echo "Removing bundled tools for Lite version..."
...
echo "TVMax-$VARIANT.AppImage created."
...
echo "All builds completed!"
