#!/bin/bash
set -e

# Configuration
APP_NAME="tvmax"
VERSION="1.0.0"
ARCH="amd64"
BUILD_DIR="../build/linux/x64/release/bundle"
DEB_DIR="${APP_NAME}_${VERSION}_${ARCH}"

echo "Starting DEB creation for $APP_NAME v$VERSION..."
...
echo "Preparing directory structure..."
...
    echo "Error: Build directory not found! Please run 'flutter build linux' first."
...
echo "Copying application files..."
...
echo "Creating symlink..."
...
echo "Creating control file..."
...
echo "Creating desktop entry..."
...
echo "Copying icon..."
...
    echo "Icon master not found, looking for alternative..."
...
echo "Building .deb package..."
...
echo "${DEB_DIR}.deb created successfully!"
